language: node_js

cache:
  directories:
    - node_modules
    - $HOME/.npm

notifications:
  email: false

node_js:
  - '8.9.4'

before_install:
  - npm i -g npm@^5.6.0

script:
  - npm test

after_success:
  - ./deploy.sh